var N = null;var sourcesIndex = {};
sourcesIndex["pallet_amm"] = {"name":"","files":["lib.rs","weights.rs"]};
sourcesIndex["pallet_crowdloans"] = {"name":"","files":["lib.rs","types.rs","weights.rs"]};
sourcesIndex["pallet_currency_adapter"] = {"name":"","files":["lib.rs"]};
sourcesIndex["pallet_liquid_staking"] = {"name":"","files":["lib.rs","types.rs","weights.rs"]};
sourcesIndex["pallet_liquidation"] = {"name":"","files":["lib.rs"]};
sourcesIndex["pallet_liquidity_mining"] = {"name":"","files":["lib.rs","weights.rs"]};
sourcesIndex["pallet_loans"] = {"name":"","files":["interest.rs","lib.rs","ptoken.rs","rate_model.rs","types.rs","weights.rs"]};
sourcesIndex["pallet_loans_rpc"] = {"name":"","files":["lib.rs"]};
sourcesIndex["pallet_loans_rpc_runtime_api"] = {"name":"","files":["lib.rs"]};
sourcesIndex["pallet_nominee_election"] = {"name":"","files":["lib.rs","weights.rs"]};
sourcesIndex["pallet_prices"] = {"name":"","files":["lib.rs","weights.rs"]};
sourcesIndex["pallet_router"] = {"name":"","files":["lib.rs","weights.rs"]};
sourcesIndex["parallel_primitives"] = {"name":"","files":["currency.rs","lib.rs","network.rs","tokens.rs","ump.rs"]};
createSourceSidebar();
